// Code generated by logcopter-gen; DO NOT EDIT.

package githubapi

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.goja-github-actions.pkg.githubapi")
